version: '3'

services:
    mariadb:
        image: "mariadb:10.5"
        container_name: profit_calculator_mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=profit_calculator
            - MYSQL_USER=profit_calculator
            - MYSQL_PASSWORD=profit_calculator
            - MYSQL_TCP_PORT=3307
        ports:
            - 3307:3307
        volumes:
            - mariadb_data:/var/lib/mysql
        healthcheck:
            test: ["CMD", "mysqladmin", "-uroot", "-proot", "ping"]
            interval: 10s
            timeout: 5s
            retries: 3

volumes:
  mariadb_data:
    driver: local